"""
DOCX Exporter - Export draft SAR to Word document
Include clean text, footnotes, and optional suggestions/annex
"""

from typing import Dict, List, Any
from pathlib import Path


class DOCXExporter:
    def __init__(self):
        pass
    
    def export_to_docx(
        self,
        draft: Dict[str, Any],
        output_path: str,
        include_suggestions: bool = False,
        include_footnotes: bool = True,
        include_annex: bool = False
    ):
        """Export draft to DOCX file"""
        
        try:
            from docx import Document
            from docx.shared import Pt, Inches, RGBColor
            from docx.enum.text import WD_ALIGN_PARAGRAPH
            
            doc = Document()
            
            # Add title
            title = doc.add_heading('EQUIS Self-Assessment Report 2026', 0)
            title.alignment = WD_ALIGN_PARAGRAPH.CENTER
            
            # Add metadata
            doc.add_paragraph(f"Generated: {draft.get('metadata', {}).get('generation_date', 'N/A')}")
            doc.add_paragraph(f"Source: {draft.get('metadata', {}).get('source_file', 'N/A')}")
            doc.add_paragraph()
            
            # Table of contents placeholder
            doc.add_heading('Table of Contents', 1)
            toc_para = doc.add_paragraph('[Table of contents will be generated by Word]')
            toc_para.italic = True
            doc.add_page_break()
            
            # Add sections
            for section in draft.get('sections', []):
                self._add_section_to_doc(
                    doc,
                    section,
                    include_suggestions,
                    include_footnotes
                )
            
            # Add suggestions annex if requested
            if include_annex:
                doc.add_page_break()
                self._add_suggestions_annex(doc, draft)
            
            # Save document
            doc.save(output_path)
            
        except Exception as e:
            raise Exception(f"Error exporting to DOCX: {str(e)}")
    
    def _add_section_to_doc(
        self,
        doc,
        section: Dict[str, Any],
        include_suggestions: bool,
        include_footnotes: bool
    ):
        """Add a section to the document"""
        from docx.shared import Pt, RGBColor
        from docx.oxml.ns import qn
        
        # Add heading
        level = min(section.get('level', 1), 3)  # Max heading level 3
        heading_text = f"{section.get('number', '')} {section.get('title', '')}".strip()
        
        heading = doc.add_heading(heading_text, level)
        
        # Add content
        content = section.get('content', '')
        
        if content:
            para = doc.add_paragraph(content)
            
            # Add evidence footnotes if enabled
            if include_footnotes and section.get('evidence_links'):
                for evidence in section['evidence_links']:
                    if evidence.get('confidence', 0) > 0.6:
                        # Add footnote
                        run = para.add_run(f" [Evidence: {evidence['filename']}]")
                        run.font.size = Pt(9)
                        run.font.color.rgb = RGBColor(100, 100, 100)
        
        # Add suggestions if enabled
        if include_suggestions and section.get('suggestions'):
            doc.add_paragraph()
            suggestions_heading = doc.add_paragraph()
            run = suggestions_heading.add_run('AI Suggestions:')
            run.bold = True
            run.font.color.rgb = RGBColor(0, 100, 200)
            
            for suggestion in section['suggestions']:
                self._add_suggestion_to_doc(doc, suggestion)
        
        # Add coverage info
        if section.get('coverage_score', 0) > 0:
            coverage_para = doc.add_paragraph()
            run = coverage_para.add_run(
                f"EQUIS Coverage: {section['coverage_score']:.0f}% | "
                f"Criteria: {', '.join(section.get('equis_criteria', []))}"
            )
            run.font.size = Pt(9)
            run.italic = True
            run.font.color.rgb = RGBColor(100, 100, 100)
        
        doc.add_paragraph()  # Spacing
    
    def _add_suggestion_to_doc(self, doc, suggestion: Dict[str, Any]):
        """Add a suggestion to the document"""
        from docx.shared import Pt, RGBColor
        
        para = doc.add_paragraph(style='List Bullet')
        
        # Suggestion type
        sug_type = suggestion.get('type', 'edit').upper()
        run = para.add_run(f"[{sug_type}] ")
        run.bold = True
        
        # Suggestion text
        if suggestion.get('original_text'):
            para.add_run(f"Change: \"{suggestion['original_text'][:50]}...\" → ")
        
        sug_text = suggestion.get('suggested_text', '')
        if len(sug_text) > 100:
            sug_text = sug_text[:100] + "..."
        para.add_run(f"\"{sug_text}\"")
        
        # Rationale
        para.add_paragraph()
        rationale_para = doc.add_paragraph(suggestion.get('rationale', ''), style='List Bullet 2')
        rationale_para.runs[0].font.size = Pt(9)
        rationale_para.runs[0].italic = True
        
        # EQUIS clause
        if suggestion.get('equis_clause'):
            clause_para = doc.add_paragraph(
                f"EQUIS Clause {suggestion.get('equis_clause_number', '')}: {suggestion['equis_clause']}",
                style='List Bullet 2'
            )
            clause_para.runs[0].font.size = Pt(9)
            clause_para.runs[0].font.color.rgb = RGBColor(0, 100, 0)
    
    def _add_suggestions_annex(self, doc, draft: Dict[str, Any]):
        """Add an annex with all suggestions and decision log"""
        from docx.shared import Pt, RGBColor
        
        doc.add_heading('Annex: AI Suggestions and Decision Log', 1)
        
        doc.add_paragraph(
            "This annex contains all AI-generated suggestions made during the SAR drafting process, "
            "along with the decisions made (accepted/rejected)."
        )
        
        for section in draft.get('sections', []):
            if not section.get('suggestions'):
                continue
            
            doc.add_heading(
                f"{section.get('number', '')} {section.get('title', '')}",
                2
            )
            
            for suggestion in section['suggestions']:
                para = doc.add_paragraph(style='List Number')
                
                # Status
                status = "✓ ACCEPTED" if suggestion.get('accepted') else "✗ REJECTED" if suggestion.get('accepted') is False else "⊘ PENDING"
                run = para.add_run(f"{status} - ")
                run.bold = True
                
                if suggestion.get('accepted'):
                    run.font.color.rgb = RGBColor(0, 150, 0)
                elif suggestion.get('accepted') is False:
                    run.font.color.rgb = RGBColor(150, 0, 0)
                
                # Suggestion details
                para.add_run(f"{suggestion.get('rationale', '')}")
                
                # Add details
                detail_para = doc.add_paragraph(style='List Bullet 2')
                detail_para.add_run(f"Type: {suggestion.get('type', 'N/A')} | ")
                detail_para.add_run(f"Confidence: {suggestion.get('confidence', 0):.0%}")
                
                if suggestion.get('equis_clause_number'):
                    detail_para.add_run(f" | EQUIS: {suggestion['equis_clause_number']}")
